# Generated by Django 5.2 on 2026-04-04 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.usercreate')),
            ],
            options={
                'unique_together': {('user', 'property')},
            },
        ),
    ]
