# Generated by Django 5.2 on 2026-04-28 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0011_alter_usercreate_id'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='property_type',
            field=models.CharField(blank=True, choices=[('user_property', 'User Property'), ('agent_property', 'Agent Property')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='property_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='developer.usercreate'),
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='property',
        ),
    ]
