# Generated by Django 5.2 on 2026-04-28 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_wishlist_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='property_type',
        ),
    ]
