# Generated by Django 5.2.5 on 2026-04-08 10:26

import cloudinary.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pin_code', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('messages_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AgentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('land_area', models.CharField(max_length=255)),
                ('sq_ft', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('screenshot', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('perprice', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(max_length=50)),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=255)),
                ('land_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('taluk', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenities', models.ManyToManyField(blank=True, related_name='agent_properties', to='developer.amenities')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.category')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.purpose')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPropertyFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.subcategoryfield')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='agents.agentproperty')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentproperty')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPropertyLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='agents.agentproperty')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPropertySellingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_points', to='agents.agentproperty')),
            ],
        ),
        migrations.CreateModel(
            name='AgentUserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128, null=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin_code', models.IntegerField()),
                ('profile_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('avatar_url', models.URLField(blank=True, null=True)),
                ('professional_title', models.CharField(blank=True, max_length=150, null=True)),
                ('professional_bio', models.TextField(blank=True, null=True)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('properties_listed', models.IntegerField(default=0)),
                ('deals_closed', models.IntegerField(default=0)),
                ('is_agent', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('agent_type', models.CharField(choices=[('basic', 'Basic Agent'), ('premium', 'Premium Agent'), ('elite', 'Elite Agent')], default='basic', max_length=20)),
                ('paid', models.BooleanField(default=False)),
                ('plan_start_date', models.DateTimeField(blank=True, null=True)),
                ('plan_expiry_date', models.DateTimeField(blank=True, null=True)),
                ('operating_cities', models.JSONField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_code', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('elite_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.eliteplan')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.premiumplan')),
                ('specializations', models.ManyToManyField(blank=True, to='developer.category')),
            ],
        ),
        migrations.CreateModel(
            name='AgentReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.FloatField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_reviews', to='developer.usercreate')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.usercreate')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='agents.agentuserprofile')),
            ],
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentuserprofile'),
        ),
        migrations.CreateModel(
            name='AgentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_contacts', to='developer.usercreate')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='agents.agentuserprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PendingAgentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('agent_type', models.CharField(choices=[('basic', 'Basic Agent'), ('premium', 'Premium Agent'), ('elite', 'Elite Agent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('elite_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.eliteplan')),
                ('premium_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.premiumplan')),
            ],
        ),
    ]
