# Generated by Django 5.2.5 on 2026-04-02 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_contacts', to='developer.usercreate'),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.category'),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.purpose'),
        ),
        migrations.AddField(
            model_name='agentpropertyimage',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentproperty'),
        ),
        migrations.AddField(
            model_name='agentregister',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.premiumplan'),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='elite_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.eliteplan'),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.premiumplan'),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='specializations',
            field=models.ManyToManyField(blank=True, to='developer.category'),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agents.agentuserprofile'),
        ),
        migrations.AddField(
            model_name='agentcontact',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='agents.agentuserprofile'),
        ),
    ]
