<<<<<<< HEAD
# Generated by Django 5.2.5 on 2026-03-18 11:40
=======
# Generated by Django 5.2 on 2026-03-25 06:40
>>>>>>> ff17e703800e6b587c721487acfaa7a4b8a8e903

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='developer.premium'),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.category'),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.purpose'),
        ),
        migrations.AddField(
            model_name='agentpropertyimage',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentproperty'),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='elite_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='developer.eliteplan'),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='premium_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='developer.premiumplan'),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agents.inbox'),
        ),
    ]
