# Generated by Django 5.2 on 2026-03-11 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='developer.premium'),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.category'),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.purpose'),
        ),
        migrations.AddField(
            model_name='agentpropertyimage',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentproperty'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='developer.premium'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='messages',
            field=models.ManyToManyField(blank=True, related_name='agents', to='agents.inbox'),
        ),
    ]
