# Generated by Django 5.2.5 on 2026-03-26 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('developer', '0002_alter_premiumplan_bulk_whatsapp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='developer.premiumplan'),
        ),
    ]
