# Generated by Django 5.2 on 2026-05-09 04:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentproperty',
            name='uuid',
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
