# Generated by Django 5.2.5 on 2026-03-16 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
        ('developer', '0003_advertisement'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='AgentUserProfile',
        ),
    ]
