# Generated by Django 5.2.5 on 2026-04-17 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='property_hash_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
