# Generated by Django 5.2 on 2026-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
