# Generated by Django 5.2.5 on 2026-04-17 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentproperty_property_hash_id'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPropertyEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='agents.agentproperty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_property_enquiries', to='developer.usercreate')),
            ],
        ),
    ]
