# Generated by Django 5.2.5 on 2026-03-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_rename_userprofile_agentuserprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='agent_type',
            field=models.CharField(choices=[('basic', 'Basic Agent'), ('premium', 'Premium Agent'), ('elite', 'Elite Agent')], default='basic', max_length=20),
        ),
    ]
