# Generated by Django 5.2.5 on 2026-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentuserprofile_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
