# Generated by Django 5.2 on 2026-04-27 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentproperty_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
