# Generated by Django 5.2.5 on 2026-03-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agentregister'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='areas_served',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='deals_closed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='properties_listed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='operating_cities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
