# Generated by Django 5.2.5 on 2026-04-03 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_alter_agentproperty_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
