# Generated by Django 5.2.5 on 2026-04-03 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentuserprofile_is_active'),
        ('developer', '0003_alter_category_name_alter_purpose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentproperty',
            name='amenities',
        ),
        migrations.CreateModel(
            name='AgentPropertyLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='agents.agentproperty')),
            ],
        ),
        migrations.CreateModel(
            name='AgentPropertySellingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_points', to='agents.agentproperty')),
            ],
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='agent_properties', to='developer.amenities'),
        ),
    ]
