# Generated by Django 5.2.5 on 2026-03-16 11:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentuserprofile_agent_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentuserprofile',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
