# Generated by Django 5.2.5 on 2026-03-28 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentuserprofile_areas_served_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='areas_served',
        ),
    ]
