# Generated by Django 5.2.5 on 2026-03-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agentuserprofile_professional_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
