# Generated by Django 5.2 on 2026-04-27 11:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_agentproperty_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
