# Generated by Django 5.2 on 2026-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_inbox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
