# Generated by Django 5.2 on 2026-04-30 08:29

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agentproperty_uuid'),
        ('developer', '0012_alter_advertisement_feature_alter_advertisement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcontact',
            name='contact_number',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='agentcontact',
            name='email',
            field=models.EmailField(max_length=254, validators=[developer.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='agentcontact',
            name='first_name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='agentcontact',
            name='last_name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='agentcontact',
            name='message',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='city',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='description',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='district',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='label',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='land_area',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='land_mark',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='location',
            field=models.TextField(validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='perprice',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='pincode',
            field=models.CharField(max_length=50, validators=[developer.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='price',
            field=models.CharField(max_length=50, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='taluk',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='agentpropertyenquiry',
            name='email',
            field=models.EmailField(max_length=254, validators=[developer.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='agentpropertyenquiry',
            name='message',
            field=models.TextField(blank=True, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='agentpropertyenquiry',
            name='name',
            field=models.CharField(max_length=150, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='agentpropertyenquiry',
            name='phone',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='agentpropertyfieldvalue',
            name='value',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentpropertylandmark',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentpropertylandmark',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentpropertysellingpoint',
            name='point',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentreview',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='developer.usercreate'),
        ),
        migrations.AlterField(
            model_name='agentreview',
            name='review',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='address',
            field=models.TextField(validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True, validators=[developer.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='password',
            field=models.CharField(max_length=128, null=True, validators=[developer.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='professional_bio',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='professional_title',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[developer.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='email',
            field=models.EmailField(max_length=254, validators=[developer.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='first_name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='last_name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='message',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='contactrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='contact',
            field=models.CharField(max_length=50, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='messages_text',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='name',
            field=models.CharField(max_length=50, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='inbox',
            name='pin_code',
            field=models.CharField(max_length=50, validators=[developer.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='pendingagentregistration',
            name='address',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='pendingagentregistration',
            name='city',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='pendingagentregistration',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[developer.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='pendingagentregistration',
            name='full_name',
            field=models.CharField(max_length=150, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='pendingagentregistration',
            name='password',
            field=models.CharField(max_length=128, validators=[developer.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='pendingagentregistration',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='pendingagentregistration',
            name='pin_code',
            field=models.CharField(max_length=10, validators=[developer.validators.validate_pincode]),
        ),
    ]
