# Generated by Django 5.2.5 on 2026-04-03 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agentproperty_amenities_agentpropertylandmark_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AgentRegister',
        ),
    ]
