# Generated by Django 5.2 on 2026-06-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agentproperty_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingagentregistration',
            name='deals_closed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pendingagentregistration',
            name='years_of_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
