# Generated by Django 5.2.5 on 2026-03-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_remove_agentuserprofile_areas_served'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='social_media',
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
    ]
