# Generated by Django 5.2.5 on 2026-03-16 11:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_agentuserprofile_profile_image'),
        ('developer', '0003_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='login',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to='developer.premium'),
        ),
    ]
