# Generated by Django 5.2.5 on 2026-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_agentuserprofile_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='login',
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='password',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
    ]
