# Generated by Django 5.2.5 on 2026-04-03 12:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_delete_agentregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingAgentRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=10)),
                ('agent_type', models.CharField(choices=[('basic', 'Basic Agent'), ('premium', 'Premium Agent'), ('elite', 'Elite Agent')], max_length=20)),
                ('plan_name', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
