# Generated by Django 5.2.5 on 2026-03-30 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_remove_agentuserprofile_social_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='messages',
        ),
    ]
