# Generated by Django 5.2 on 2026-04-30 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_alter_agentcontact_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentpropertyenquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
