# Generated by Django 5.2.5 on 2026-03-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_remove_agentuserprofile_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='linkedin',
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='website',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
