# Generated by Django 5.2.5 on 2026-04-04 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_pendingagentregistration'),
        ('developer', '0003_alter_category_name_alter_purpose_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.subcategory'),
        ),
        migrations.CreateModel(
            name='AgentPropertyFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.subcategoryfield')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='agents.agentproperty')),
            ],
        ),
    ]
