# Generated by Django 5.2 on 2026-06-13 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_pendingagentregistration_submitted_by'),
        ('developer', '0045_alter_property_district_alter_property_land_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingagentregistration',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_agent_registrations', to='developer.usercreate'),
        ),
    ]
