# Generated by Django 5.2.5 on 2026-03-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_remove_agentuserprofile_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='operating_cities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='professional_bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='social_media',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='specializations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
