# Generated by Django 5.2 on 2026-04-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_agentpropertyenquiry_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentpropertyenquiry',
            old_name='agent_property',
            new_name='property',
        ),
    ]
