# Generated by Django 5.2.5 on 2026-04-04 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentproperty_subcategory_agentpropertyfieldvalue'),
        ('developer', '0003_alter_category_name_alter_purpose_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingagentregistration',
            name='plan_name',
        ),
        migrations.AddField(
            model_name='pendingagentregistration',
            name='elite_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.eliteplan'),
        ),
        migrations.AddField(
            model_name='pendingagentregistration',
            name='premium_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.premiumplan'),
        ),
    ]
