# Generated by Django 5.2.5 on 2026-03-30 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_remove_agentuserprofile_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agentuserprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
