# Generated by Django 5.2.5 on 2026-03-18 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agentuserprofile_operating_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='agent_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
