# Generated by Django 5.2 on 2026-05-01 09:09

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_rename_agent_property_agentpropertyenquiry_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcontact',
            name='last_name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_name]),
        ),
    ]
