# Generated by Django 5.2 on 2026-06-15 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_alter_pendingagentregistration_submitted_by'),
        ('developer', '0045_alter_property_district_alter_property_land_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='developer.subscription'),
        ),
    ]
