# Generated by Django 5.2 on 2026-05-01 09:15

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_alter_agentcontact_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcontact',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_name]),
        ),
    ]
