# Generated by Django 5.2 on 2026-06-25 07:03

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentproperty_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='id',
            field=models.UUIDField(db_index=True, default=agents.models.generate_global_property_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
