# Generated by Django 5.2.5 on 2025-11-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0009_agentproperty_screenshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='perprice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
