# Generated by Django 5.2.5 on 2026-03-30 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_agentcontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentuserprofile',
            old_name='agent_code',
            new_name='agent_id',
        ),
    ]
