# Generated by Django 5.2 on 2026-05-01 10:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentcontact_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentcontact',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
