# Generated by Django 5.2.5 on 2025-11-26 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentproperty_perprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='city',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='district',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='label',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='land_area',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='land_mark',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='location',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='perprice',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='phone',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='pincode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='price',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='sq_ft',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='whatsapp',
            field=models.CharField(max_length=250),
        ),
    ]
