# Generated by Django 5.2 on 2026-08-19 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentproperty_id'),
        ('developer', '0063_alter_expiredproperty_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingagentregistration',
            name='basic_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.agentplan'),
        ),
    ]
