# Generated by Django 5.2.5 on 2026-03-30 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_rename_agent_code_agentuserprofile_agent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentuserprofile',
            old_name='agent_id',
            new_name='agent_code',
        ),
    ]
