# Generated by Django 5.2 on 2026-05-06 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agentcontact_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='reset_token',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
