# Generated by Django 5.2 on 2026-08-05 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_agentproperty_admin_note_agentproperty_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentproperty',
            name='admin_note',
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='expiry_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
