# Generated by Django 5.2.5 on 2025-11-26 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0011_alter_agentproperty_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='location',
            field=models.CharField(max_length=2000),
        ),
    ]
