# Generated by Django 5.2.5 on 2026-03-30 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_rename_agent_id_agentuserprofile_agent_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentpropertyimage',
            name='property',
        ),
        migrations.DeleteModel(
            name='AgentProperty',
        ),
        migrations.DeleteModel(
            name='AgentPropertyImage',
        ),
    ]
