# Generated by Django 5.2 on 2026-08-19 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agentuserprofile_basic_plan'),
        ('agents', '0012_remove_agentproperty_admin_note_and_more'),
    ]

    operations = [
    ]
