# Generated by Django 5.2 on 2026-05-07 09:53

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0012_agentuserprofile_reset_otp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='deposit',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_safe_text]),
        ),
    ]
