# Generated by Django 5.2.5 on 2026-03-30 10:14

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_remove_agentpropertyimage_property_and_more'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('land_area', models.CharField(max_length=255)),
                ('sq_ft', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('amenities', models.CharField(blank=True, max_length=500, null=True)),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('perprice', models.FloatField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('whatsapp', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('location', models.TextField()),
                ('city', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=255)),
                ('land_mark', models.CharField(blank=True, max_length=255, null=True)),
                ('owner', models.CharField(blank=True, max_length=255, null=True)),
                ('taluk', models.CharField(blank=True, max_length=255, null=True)),
                ('village', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('screenshot', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agents.agentuserprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.category')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_properties', to='developer.purpose')),
            ],
        ),
    ]
