# Generated by Django 5.2 on 2026-08-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_merge_20260819_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentproperty',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='agentproperty',
            name='expired_at',
        ),
        migrations.RemoveField(
            model_name='agentproperty',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='agentproperty',
            name='expiry_reason',
        ),
        migrations.RemoveField(
            model_name='agentproperty',
            name='status',
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='duration_days',
            field=models.IntegerField(default=30),
        ),
    ]
