# Generated by Django 5.2 on 2026-05-08 05:53

import developer.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_agentproperty_deposit'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, validators=[developer.validators.validate_agent_name, developer.validators.validate_safe_text])),
                ('message', models.TextField(validators=[developer.validators.validate_safe_message])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied')], default='pending', max_length=20)),
                ('replied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='agents.agentuserprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
