# Generated by Django 5.2 on 2025-11-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0013_alter_agentproperty_amenities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='taluk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='amenities',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
