# Generated by Django 5.2 on 2026-08-20 07:20

import agents.models
import cloudinary.models
import developer.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_remove_agentproperty_approved_at_and_more'),
        ('developer', '0063_alter_expiredproperty_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agents.agentuserprofile'),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='location',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.CreateModel(
            name='ExpiredAgentProperty',
            fields=[
                ('id', models.UUIDField(db_index=True, default=agents.models.generate_global_property_uuid, editable=False, primary_key=True, serialize=False)),
                ('property_hash_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('label', models.CharField(max_length=255, validators=[developer.validators.validate_safe_text])),
                ('land_area', models.CharField(max_length=255, validators=[developer.validators.validate_safe_text])),
                ('sq_ft', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(validators=[developer.validators.validate_safe_message])),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('screenshot', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('perprice', models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_safe_text])),
                ('price', models.CharField(max_length=50, validators=[developer.validators.validate_safe_text])),
                ('deposit', models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_safe_text])),
                ('whatsapp', models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_phone_number])),
                ('phone', models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_phone_number])),
                ('location', models.TextField(validators=[developer.validators.validate_safe_text])),
                ('city', models.CharField(max_length=255, validators=[developer.validators.validate_safe_text])),
                ('pincode', models.CharField(max_length=50, validators=[developer.validators.validate_pincode])),
                ('district', models.CharField(max_length=255, validators=[developer.validators.validate_safe_text])),
                ('land_mark', models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text])),
                ('owner', models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text])),
                ('taluk', models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text])),
                ('village', models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text])),
                ('state', models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text])),
                ('paid', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('notes', models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_message])),
                ('duration_days', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_properties', to='agents.agentuserprofile')),
                ('amenities', models.ManyToManyField(blank=True, related_name='expired_agent_properties', to='developer.amenities')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_agent_properties', to='developer.category')),
                ('purpose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_agent_properties', to='developer.purpose')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expired_agent_properties', to='developer.subcategory')),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expired_properties', to='developer.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredAgentPropertyFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, validators=[developer.validators.validate_safe_text])),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.subcategoryfield')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='agents.expiredagentproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredAgentPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.expiredagentproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredAgentPropertyLandmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, validators=[developer.validators.validate_safe_text])),
                ('distance', models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_safe_text])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='agents.expiredagentproperty')),
            ],
        ),
        migrations.CreateModel(
            name='ExpiredAgentPropertySellingPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.CharField(max_length=255, validators=[developer.validators.validate_safe_text])),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selling_points', to='agents.expiredagentproperty')),
            ],
        ),
    ]
