# Generated by Django 5.2.5 on 2026-03-30 10:14

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_agentproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentPropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agents.agentproperty')),
            ],
        ),
    ]
