# Generated by Django 5.2 on 2026-05-08 07:03

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0014_agentcontactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontactmessage',
            name='agent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, validators=[developer.validators.validate_email]),
        ),
        migrations.AddField(
            model_name='agentcontactmessage',
            name='agent_name',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_agent_name, developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='agentcontactmessage',
            name='agent_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AddField(
            model_name='agentcontactmessage',
            name='agent_whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[developer.validators.validate_phone_number]),
        ),
    ]
