# Generated by Django 5.2 on 2026-08-20 09:48

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0015_alter_agentproperty_agent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredagentproperty',
            name='location',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_text]),
        ),
    ]
