# Generated by Django 5.2 on 2026-09-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_alter_expiredagentproperty_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='property_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expiredagentproperty',
            name='property_code',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
