# Generated by Django 5.2.5 on 2026-03-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0016_alter_agentproperty_perprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='agentproperty',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
