# Generated by Django 5.2 on 2026-09-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_agentproperty_property_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='property_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='expiredagentproperty',
            name='property_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
