# Generated by Django 5.2.5 on 2026-04-01 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0017_alter_agentproperty_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan_commercial_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan_residential_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan_total_listing',
            field=models.IntegerField(default=0),
        ),
    ]
