# Generated by Django 5.2.5 on 2026-04-01 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_agentuserprofile_plan_commercial_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='plan_commercial_limit',
        ),
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='plan_end_date',
        ),
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='plan_residential_limit',
        ),
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='plan_start_date',
        ),
        migrations.RemoveField(
            model_name='agentuserprofile',
            name='plan_total_listing',
        ),
    ]
