# Generated by Django 5.2 on 2026-09-10 07:30

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0018_alter_agentproperty_property_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_pincode]),
        ),
    ]
