# Generated by Django 5.2.5 on 2026-04-01 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_remove_agentuserprofile_plan_commercial_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentuserprofile',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
