# Generated by Django 5.2 on 2026-09-10 09:11

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0019_alter_agentproperty_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentproperty',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='market_staff',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='agentproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
