# Generated by Django 5.2.5 on 2026-04-01 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_agentuserprofile_plan_expiry_date_and_more'),
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='elite_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.eliteplan'),
        ),
    ]
