# Generated by Django 5.2 on 2026-09-10 10:04

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0020_agentproperty_added_by_agentproperty_market_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredagentproperty',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='expiredagentproperty',
            name='market_staff',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
    ]
