# Generated by Django 5.2 on 2026-09-10 10:19

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_expiredagentproperty_added_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredagentproperty',
            name='pincode',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_pincode]),
        ),
    ]
