# Generated by Django 5.2.5 on 2026-04-02 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0021_agentuserprofile_elite_plan'),
        ('developer', '0007_rename_sale_eliteplan_commercial_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcontact',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_contacts', to='developer.usercreate'),
        ),
    ]
