# Generated by Django 5.2 on 2026-09-11 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0022_alter_expiredagentproperty_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentuserprofile',
            name='total_property_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
