# Generated by Django 5.2 on 2026-09-11 10:15

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0023_agentuserprofile_total_property_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentproperty',
            name='land_area',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
    ]
