# Generated by Django 5.2.5 on 2026-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliteplan',
            name='plan_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='plan_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
