# Generated by Django 5.2.5 on 2026-04-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliteplan',
            old_name='created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='eliteplan',
            old_name='validity',
            new_name='plan_validity_days',
        ),
        migrations.RemoveField(
            model_name='eliteplan',
            name='Bulk_whatsapp',
        ),
        migrations.RemoveField(
            model_name='eliteplan',
            name='Poster',
        ),
        migrations.RemoveField(
            model_name='eliteplan',
            name='commercial_limit',
        ),
        migrations.RemoveField(
            model_name='eliteplan',
            name='lead_follow',
        ),
        migrations.RemoveField(
            model_name='eliteplan',
            name='meta_ads',
        ),
        migrations.RemoveField(
            model_name='eliteplan',
            name='residential_limit',
        ),
        migrations.RemoveField(
            model_name='eliteplan',
            name='social_media',
        ),
        migrations.RemoveField(
            model_name='eliteplan',
            name='total_listing',
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='bulk_whatsapp_messages',
            field=models.CharField(default='Not included', help_text='Bulk WhatsApp messages feature', max_length=255),
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='lead_followup_support',
            field=models.CharField(default='Not included', help_text='Lead follow-up support description', max_length=255),
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='meta_ads_promotion',
            field=models.CharField(default='Not included', help_text='Meta Ads promotion details', max_length=255),
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='poster_creation',
            field=models.CharField(default='Not included', help_text='Poster creation details', max_length=255),
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='sale_listings_limit',
            field=models.PositiveIntegerField(default=10, help_text='Number of sale listings allowed'),
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='social_media_marketing',
            field=models.CharField(default='Not included', help_text='Social media marketing support', max_length=255),
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='total_property_listings',
            field=models.PositiveIntegerField(default=0, help_text='Total number of property listings allowed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='lead_management',
            field=models.CharField(default='Not included', help_text='Lead management description', max_length=255),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='price',
            field=models.PositiveIntegerField(help_text='Plan price in currency unit'),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='priority_search',
            field=models.CharField(default='Not included', help_text='Priority search feature description', max_length=255),
        ),
    ]
