# Generated by Django 5.2 on 2026-03-18 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElitePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('validity', models.PositiveIntegerField(help_text='Plan validity in days')),
                ('total_listing', models.PositiveIntegerField()),
                ('sale', models.PositiveIntegerField(default=10)),
                ('priority_search', models.CharField(max_length=255)),
                ('meta_ads', models.CharField(max_length=255)),
                ('Bulk_whatsapp', models.CharField(max_length=255)),
                ('Poster', models.CharField(max_length=255)),
                ('social_media', models.CharField(max_length=255)),
                ('lead_follow', models.CharField(max_length=255)),
                ('lead_management', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
