# Generated by Django 5.2 on 2026-03-12 09:49

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='buysel/profile_images/person', max_length=255, null=True, verbose_name='image'),
        ),
    ]
