# Generated by Django 5.2.5 on 2026-04-08 05:22

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryfield',
            name='field_ui',
            field=models.CharField(blank=True, choices=[('dropdown', 'Dropdown'), ('button_group', 'Button Group'), ('checkbox', 'Checkbox')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subcategoryfield',
            name='options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategoryfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Yes/No'), ('select', 'Select'), ('multi_select', 'Multi Select')], max_length=50),
        ),
        migrations.AlterField(
            model_name='subcategoryfield',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon'),
        ),
        migrations.AlterField(
            model_name='subcategoryfield',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.subcategory'),
        ),
    ]
