# Generated by Django 5.2.5 on 2026-04-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='best_suited_for',
            field=models.CharField(blank=True, help_text='Example: Agents / Builders / Individuals', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='bulk_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='edit_option',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='lead_followup_support',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='matching_clients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='meta_ads_promotion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='no_of_enquiries',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='no_of_listings',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='offline_agent_share',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='poster_creation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='property_visibility',
            field=models.CharField(blank=True, help_text='Example: High / Medium / Low', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='social_media_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userplan',
            name='top_priority_search',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='validity',
            field=models.PositiveIntegerField(help_text='Plan validity in days'),
        ),
    ]
