# Generated by Django 5.2 on 2026-03-10 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='Amount',
            new_name='amount',
        ),
    ]
