# Generated by Django 5.2 on 2026-04-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='useradd',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
