# Generated by Django 5.2 on 2026-03-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_amenities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expiredproperty',
            name='amenities',
        ),
        migrations.RemoveField(
            model_name='property',
            name='amenities',
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='expired_properties', to='developer.amenities'),
        ),
        migrations.AddField(
            model_name='property',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='properties', to='developer.amenities'),
        ),
    ]
