# Generated by Django 5.2.5 on 2026-04-08 05:53

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_subcategoryfield_field_ui_subcategoryfield_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryfield',
            name='options',
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='developer.subcategoryfield')),
            ],
        ),
    ]
