# Generated by Django 5.2 on 2026-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_userprofile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
