# Generated by Django 5.2 on 2026-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_propertyview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderBannerAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='slider_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
