# Generated by Django 5.2.5 on 2026-04-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_rename_created_eliteplan_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
