# Generated by Django 5.2.5 on 2026-03-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_premiumplan_bulk_whatsapp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premiumplan',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
