# Generated by Django 5.2 on 2026-04-24 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_useradd_email_alter_useradd_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradd',
            name='max_pay_per_listing',
            field=models.PositiveIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='useradd',
            name='pay_per_listing_amount',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.AddField(
            model_name='useradd',
            name='pay_per_listing_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useradd',
            name='plan_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='useradd',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.CreateModel(
            name='ListingPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=5000, max_digits=10)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.useradd')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.property')),
            ],
        ),
    ]
