# Generated by Django 5.2 on 2026-03-12 09:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_userprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='Vector_te4oj7', max_length=255, null=True, verbose_name='image'),
        ),
    ]
