# Generated by Django 5.2 on 2026-04-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='modal_head',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='modal_paragraph',
        ),
    ]
