# Generated by Django 5.2 on 2026-03-19 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_agentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradd',
            name='active_plan',
            field=models.CharField(choices=[('basic', 'User Plan'), ('upgrade', 'Upgraded Plan')], default='basic', max_length=10),
        ),
        migrations.AddField(
            model_name='useradd',
            name='upgrade_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.userupgrade'),
        ),
        migrations.AddField(
            model_name='useradd',
            name='user_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.userplan'),
        ),
    ]
