# Generated by Django 5.2.5 on 2026-04-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_usercreate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
