# Generated by Django 5.2.5 on 2026-04-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_alter_agentplan_bulk_whatsapp_alter_agentplan_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('package_type', models.CharField(choices=[('banner_basic', 'Basic Banner/Slider'), ('banner_pro', 'High Quality Banner/Slider')], max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ads_per_day', models.PositiveIntegerField(default=1)),
                ('display_seconds', models.PositiveIntegerField(help_text='Display duration in seconds')),
                ('is_premium_placement', models.BooleanField(default=False)),
                ('custom_branding', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReelPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reel_type', models.CharField(choices=[('short_reel', 'Short Reel (15-30 sec)'), ('cinematic_reel', 'Cinematic Reel (30-60 sec)')], max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.CharField(max_length=50)),
                ('includes_editing', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
