# Generated by Django 5.2 on 2026-03-10 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_rename_amount_userplan_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='category',
        ),
        migrations.AddField(
            model_name='userplan',
            name='category',
            field=models.ManyToManyField(to='developer.category'),
        ),
    ]
