# Generated by Django 5.2.5 on 2026-04-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0002_userplan_best_suited_for_userplan_bulk_whatsapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='best_suited_for',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='no_of_enquiries',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='no_of_listings',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='property_visibility',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='bulk_whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='edit_option',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='lead_followup_support',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='listing',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='matching_clients',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='meta_ads_promotion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='offline_agent_share',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='poster_creation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='social_media_marketing',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='top_priority_search',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='validity',
            field=models.PositiveIntegerField(),
        ),
    ]
