# Generated by Django 5.2 on 2026-03-28 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_property_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='listing',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
