# Generated by Django 5.2 on 2026-04-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_useradd_max_pay_per_listing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradd',
            name='plan_expired',
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='developer.usercreate'),
        ),
        migrations.AlterField(
            model_name='propertyenquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_enquiries', to='developer.usercreate'),
        ),
        migrations.AlterField(
            model_name='useradd',
            name='user_id',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.DeleteModel(
            name='ListingPayment',
        ),
    ]
