# Generated by Django 5.2 on 2026-05-11 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_alter_heroimage_id_alter_sliderbannerad_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HeroImage',
            new_name='BannerAd',
        ),
        migrations.RenameModel(
            old_name='SliderBannerAd',
            new_name='SliderAd',
        ),
    ]
