# Generated by Django 5.2 on 2026-03-19 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_useradd_active_plan_useradd_upgrade_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradd',
            name='active_plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('upgrade', 'Upgrade')], default='basic', max_length=10),
        ),
    ]
