# Generated by Django 5.2 on 2026-04-15 06:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_sliderbannerad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderbannerad',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
