# Generated by Django 5.2.5 on 2026-04-08 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_remove_subcategoryfield_options_fieldoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoryfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Yes/No'), ('select', 'Select'), ('multi_select', 'Multi Select'), ('countable', 'Countable')], max_length=50),
        ),
    ]
