# Generated by Django 5.2.5 on 2026-04-11 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_remove_userplan_best_suited_for_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='listing',
        ),
    ]
