# Generated by Django 5.2.5 on 2026-04-20 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_advertisementpackage_reelpackage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementpackage',
            name='custom_branding',
        ),
        migrations.RemoveField(
            model_name='advertisementpackage',
            name='is_premium_placement',
        ),
        migrations.AddField(
            model_name='advertisementpackage',
            name='ad_format',
            field=models.CharField(choices=[('banner', 'Banner'), ('slider', 'Slider')], default='banner', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='advertisementpackage',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='advertisementpackage',
            name='display_seconds',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='advertisementpackage',
            name='package_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro')], max_length=50),
        ),
    ]
