# Generated by Django 5.2 on 2026-03-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_remove_userplan_category_userplan_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userupgrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('validity', models.PositiveIntegerField()),
                ('listing', models.CharField(max_length=255)),
                ('enquiries', models.PositiveIntegerField()),
                ('Edit', models.PositiveIntegerField()),
                ('genuine', models.CharField(max_length=255)),
                ('meta', models.CharField(max_length=255)),
                ('bulk', models.CharField(max_length=255)),
                ('poster', models.CharField(max_length=255)),
                ('social_media', models.CharField(max_length=255)),
                ('lead_follow', models.CharField(max_length=255)),
                ('best', models.CharField(max_length=255)),
            ],
        ),
    ]
