# Generated by Django 5.2 on 2026-03-05 06:53

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0003_remove_expiredproperty_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='icon')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.category')),
            ],
        ),
    ]
