# Generated by Django 5.2 on 2026-05-11 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_rename_heroimage_bannerad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_paid_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='plan_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='developer.userplan'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], default='user', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_upgrade_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upgrade_user_profiles', to='developer.userupgrade'),
        ),
    ]
