# Generated by Django 5.2.5 on 2026-04-20 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_remove_advertisementpackage_custom_branding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reelpackage',
            old_name='includes_editing',
            new_name='edited_video',
        ),
        migrations.AddField(
            model_name='reelpackage',
            name='reel_format',
            field=models.CharField(choices=[('instagram', 'Instagram Reel'), ('youtube_shorts', 'YouTube Shorts'), ('tiktok', 'TikTok Style')], default='instagram', max_length=50),
        ),
    ]
