# Generated by Django 5.2 on 2026-03-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_alter_useradd_active_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradd',
            name='user_plan',
        ),
        migrations.AddField(
            model_name='useradd',
            name='user_plans',
            field=models.ManyToManyField(blank=True, to='developer.userplan'),
        ),
    ]
