# Generated by Django 5.2 on 2026-03-28 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_userplan_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='listing',
            field=models.CharField(help_text='Example: 2 Residential / 1 Commercial', max_length=255),
        ),
    ]
