# Generated by Django 5.2 on 2026-04-25 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_remove_useradd_plan_expired_alter_property_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='last_plan_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usercreate',
            name='paid_property_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usercreate',
            name='upgrade_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='developer.userupgrade'),
        ),
        migrations.AddField(
            model_name='usercreate',
            name='user_plans',
            field=models.ManyToManyField(blank=True, related_name='users', to='developer.userplan'),
        ),
    ]
