# Generated by Django 5.2.5 on 2026-04-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_remove_userplan_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='commercial_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='residential_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
