# Generated by Django 5.2 on 2026-03-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0004_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredproperty',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expired_properties', to='developer.subcategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='developer.subcategory'),
        ),
    ]
