# Generated by Django 5.2 on 2026-03-31 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_alter_userplan_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='agents',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='developer.agentplan'),
        ),
    ]
