# Generated by Django 5.2 on 2026-03-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_remove_useradd_user_plan_useradd_user_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradd',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
