# Generated by Django 5.2 on 2026-04-16 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyenquiry',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_enquiries', to='developer.useradd'),
        ),
    ]
