# Generated by Django 5.2 on 2026-03-05 07:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_expiredproperty_subcategory_property_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='icon'),
            preserve_default=False,
        ),
    ]
