# Generated by Django 5.2.5 on 2026-04-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_rename_includes_editing_reelpackage_edited_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelpackage',
            name='reel_format',
            field=models.TextField(blank=True, null=True),
        ),
    ]
