# Generated by Django 5.2 on 2026-05-11 12:37

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_userprofile_is_paid_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreate',
            name='upgrade_plan',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user_upgrade_plan',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='bulk_whatsapp',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='commercial_limit',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='edit_option',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='lead_followup_support',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='matching_clients',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='meta_ads_promotion',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='offline_agent_share',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='poster_creation',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='residential_limit',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='social_media_marketing',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='top_priority_search',
        ),
        migrations.AddField(
            model_name='userplan',
            name='best',
            field=models.CharField(blank=True, default='', help_text='Best suited for', max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='userplan',
            name='bulk',
            field=models.PositiveIntegerField(default=0, help_text='Bulk WhatsApp message count'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='edit',
            field=models.PositiveIntegerField(default=0, help_text='Number of edit options allowed'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='enquiries',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplan',
            name='genuine',
            field=models.CharField(default='', help_text='Matching genuine clients', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='userplan',
            name='lead_follow',
            field=models.CharField(default='', help_text='Lead followup support', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='userplan',
            name='listing',
            field=models.CharField(default='', help_text='Example: 2 Residential / 1 Commercial', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='userplan',
            name='meta',
            field=models.PositiveIntegerField(default=0, help_text='Meta ads promotion count'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='poster',
            field=models.PositiveIntegerField(default=0, help_text='Poster creation count'),
        ),
        migrations.AddField(
            model_name='userplan',
            name='social_media',
            field=models.CharField(default='', help_text='Social media marketing duration', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan_type',
            field=models.CharField(default='owner_plan', editable=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='validity',
            field=models.PositiveIntegerField(default=0, help_text='Plan validity in days'),
        ),
        migrations.DeleteModel(
            name='Userupgrade',
        ),
    ]
