# Generated by Django 5.2.5 on 2026-04-11 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0005_userplan_commercial_limit_userplan_residential_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='purpose',
        ),
    ]
