# Generated by Django 5.2 on 2026-04-27 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_alter_userprofile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyenquiry',
            old_name='messagebox',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='property_hash_id',
        ),
    ]
