# Generated by Django 5.2 on 2025-09-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_alter_property_perprice_alter_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='description',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
