# Generated by Django 5.2 on 2026-04-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_agents_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliteplan',
            old_name='sale',
            new_name='commercial_limit',
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='residential_limit',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
