# Generated by Django 5.2.5 on 2026-04-20 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_alter_reelpackage_reel_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reelpackage',
            name='edited_video',
        ),
    ]
