# Generated by Django 5.2 on 2026-05-12 05:12

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_remove_usercreate_upgrade_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='offline_agent_share',
            field=models.CharField(default='', help_text='Offline agent share', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='userplan',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='userplan',
            name='property_visibility',
            field=models.CharField(default='', help_text='Property visibility', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='userplan',
            name='top_priority',
            field=models.CharField(default='', help_text='Top priority search', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='userplan',
            name='total_property_listing',
            field=models.PositiveIntegerField(default=0, help_text='Total property listing count'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='best',
            field=models.CharField(blank=True, default='', help_text='Best suited for users', max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='bulk',
            field=models.PositiveIntegerField(default=0, help_text='Bulk WhatsApp count'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='edit',
            field=models.CharField(default='', help_text='Edit option', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='enquiries',
            field=models.PositiveIntegerField(default=0, help_text='Number of enquiries'),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='lead_follow',
            field=models.CharField(default='', help_text='Lead follow support', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='listing',
            field=models.CharField(default='', help_text='Residential / Commercial listing', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='social_media',
            field=models.CharField(default='', help_text='Social media marketing', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
    ]
