# Generated by Django 5.2 on 2026-03-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0006_useradd_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useradd',
            name='active_plan',
        ),
    ]
