# Generated by Django 5.2 on 2026-04-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_rename_messagebox_propertyenquiry_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
