# Generated by Django 5.2 on 2026-03-23 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_remove_useradd_active_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='developer.userplan'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='developer.useradd'),
        ),
    ]
