# Generated by Django 5.2.5 on 2026-04-14 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyenquiry',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='developer.property'),
        ),
        migrations.AddField(
            model_name='propertyenquiry',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enquiries', to='developer.usercreate'),
        ),
        migrations.AlterField(
            model_name='propertyenquiry',
            name='messagebox',
            field=models.TextField(blank=True),
        ),
    ]
