# Generated by Django 5.2 on 2026-03-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_subcategoryfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredproperty',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='dynamic_fields',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='note',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
