# Generated by Django 5.2 on 2026-05-12 07:05

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_userplan_offline_agent_share_userplan_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userplan',
            name='genuine',
        ),
        migrations.RemoveField(
            model_name='userplan',
            name='offline_agent_share',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='best',
            field=models.TextField(blank=True, default='', null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='bulk',
            field=models.TextField(default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='edit',
            field=models.CharField(default='No', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='enquiries',
            field=models.CharField(default='No', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='lead_follow',
            field=models.TextField(default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='listing',
            field=models.TextField(default='', help_text='Residential / Commercial listing', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='meta',
            field=models.TextField(default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='poster',
            field=models.CharField(default='', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='property_visibility',
            field=models.TextField(default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='social_media',
            field=models.TextField(default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='top_priority',
            field=models.TextField(default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='total_property_listing',
            field=models.CharField(default='No', help_text='Total property listings', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='validity',
            field=models.CharField(default='30 Days', help_text='Plan validity', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
    ]
