# Generated by Django 5.2 on 2026-04-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_rename_sale_eliteplan_commercial_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='key_selling_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
