# Generated by Django 5.2.7 on 2025-10-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0007_propertylist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredproperty',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
