# Generated by Django 5.2 on 2026-04-27 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_property_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
