# Generated by Django 5.2 on 2026-05-12 07:25

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_remove_userplan_genuine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplan',
            name='best',
            field=models.TextField(blank=True, db_column='best', default='', null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='best',
            new_name='best_suited_for',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='bulk',
            field=models.TextField(db_column='bulk', default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='bulk',
            new_name='bulk_whatsapp_message',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='edit',
            field=models.CharField(db_column='edit', default='No', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='edit',
            new_name='edit_option',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='enquiries',
            field=models.CharField(db_column='enquiries', default='No', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='enquiries',
            new_name='enquiry_limit',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='lead_follow',
            field=models.TextField(db_column='lead_follow', default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='lead_follow',
            new_name='lead_follow_support',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='listing',
            field=models.TextField(db_column='listing', default='', help_text='Residential / Commercial listing', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='listing',
            new_name='listing_type',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='meta',
            field=models.TextField(db_column='meta', default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='meta',
            new_name='meta_ads_promotion',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='poster',
            field=models.CharField(db_column='poster', default='', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='poster',
            new_name='poster_creation',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='top_priority',
            field=models.TextField(db_column='top_priority', default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='top_priority',
            new_name='priority_search',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='total_property_listing',
            field=models.CharField(db_column='total_property_listing', default='No', help_text='Total property listings', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='total_property_listing',
            new_name='property_listing_limit',
        ),
        migrations.AlterField(
            model_name='userplan',
            name='social_media',
            field=models.TextField(db_column='social_media', default='', validators=[developer.validators.validate_safe_text]),
        ),
        migrations.RenameField(
            model_name='userplan',
            old_name='social_media',
            new_name='social_media_marketing',
        ),
    ]
