# Generated by Django 5.2 on 2026-03-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_property_plan_alter_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
