# Generated by Django 5.2.7 on 2025-10-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_expiredproperty_state_expiredproperty_taluk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertylist',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='taluk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='propertylist',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
