# Generated by Django 5.2.5 on 2026-04-14 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_propertyenquiry_property_propertyenquiry_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='user',
        ),
        migrations.AlterField(
            model_name='propertyenquiry',
            name='messagebox',
            field=models.TextField(),
        ),
    ]
