# Generated by Django 5.2 on 2026-03-06 11:47

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0008_expiredproperty_note_property_dynamic_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoryfield',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icons'),
        ),
    ]
