# Generated by Django 5.2 on 2026-04-28 09:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0009_alter_property_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
