# Generated by Django 5.2 on 2026-05-12 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0009_alter_userplan_best_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userplan',
            old_name='edit_option',
            new_name='property_edit_option',
        ),
    ]
