# Generated by Django 5.2.5 on 2025-11-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0009_propertylist_state_propertylist_taluk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='perprice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
