# Generated by Django 5.2 on 2026-03-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0009_alter_property_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='paid',
            field=models.CharField(default='no', max_length=50),
        ),
    ]
