# Generated by Django 5.2 on 2026-03-24 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0010_alter_property_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='plan',
            new_name='package',
        ),
    ]
