# Generated by Django 5.2.5 on 2025-11-08 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0010_alter_property_perprice_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredproperty',
            name='perprice',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
