# Generated by Django 5.2 on 2026-04-28 09:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0010_alter_usercreate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
