# Generated by Django 5.2 on 2026-05-12 11:55

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0010_rename_edit_option_userplan_property_edit_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agentplan',
            name='edit',
        ),
        migrations.RemoveField(
            model_name='agentplan',
            name='enquiries',
        ),
        migrations.AddField(
            model_name='agentplan',
            name='agent_badge',
            field=models.CharField(blank=True, help_text='Badge shown for agent plan (e.g. Verified, Premium, Elite)', max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
    ]
