# Generated by Django 5.2 on 2026-05-13 09:13

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0011_remove_agentplan_edit_remove_agentplan_enquiries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deposit',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
    ]
