# Generated by Django 5.2.5 on 2025-11-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0011_alter_expiredproperty_perprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='paid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='taluk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='whatsapp',
            field=models.CharField(max_length=255),
        ),
    ]
