# Generated by Django 5.2 on 2026-04-30 07:05

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0011_alter_usercreate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='feature',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='advertisementpackage',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='advertisementpackage',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentform',
            name='category',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_category]),
        ),
        migrations.AlterField(
            model_name='agentform',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agentform',
            name='name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='agentform',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='agentplan',
            name='Bulk_whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentplan',
            name='Poster',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentplan',
            name='edit',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentplan',
            name='enquiries',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentplan',
            name='meta_ads',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentplan',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentplan',
            name='priority_search',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agentplan',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='agents',
            name='agentsemail',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='amenities',
            name='name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_head',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_blog_title]),
        ),
        migrations.AlterField(
            model_name='blog',
            name='card_paragraph',
            field=models.TextField(validators=[developer.validators.validate_blog_content]),
        ),
        migrations.AlterField(
            model_name='blogadmin',
            name='password',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='blogadmin',
            name='username',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='budget',
            name='value',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_budget]),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.CharField(max_length=500, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_text_min_3]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=14, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rate_limit',
            field=models.IntegerField(default=0, validators=[developer.validators.validate_rate_limit]),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='bulk_whatsapp_messages',
            field=models.CharField(default='Not included', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='lead_followup_support',
            field=models.CharField(default='Not included', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='lead_management',
            field=models.CharField(default='Not included', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='meta_ads_promotion',
            field=models.CharField(default='Not included', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='poster_creation',
            field=models.CharField(default='Not included', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='price',
            field=models.PositiveIntegerField(help_text='Plan price'),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='priority_search',
            field=models.CharField(default='Not included', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='eliteplan',
            name='social_media_marketing',
            field=models.CharField(default='Not included', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='password',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='phone',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='pincode',
            field=models.CharField(max_length=6, validators=[developer.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='username',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='city',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='description',
            field=models.CharField(max_length=10000, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='district',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='label',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='land_area',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='land_mark',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='market_staff',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='note',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='owner',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='paid',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='perprice',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='phone',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='pincode',
            field=models.CharField(max_length=10, validators=[developer.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='price',
            field=models.CharField(max_length=50, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='sq_ft',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='taluk',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='whatsapp',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='fieldoption',
            name='name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='premium',
            name='password',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='premium',
            name='phone',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='premium',
            name='pincode',
            field=models.CharField(max_length=6, validators=[developer.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='premium',
            name='username',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='premium',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='Bulk_whatsapp',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='Poster',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='edit',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='enquiries',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='lead_follow',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='lead_management',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='meta_ads',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='priority_search',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='premiumplan',
            name='social_media',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='feature',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='purpose',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='promotionextra',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='label',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='market_staff',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='message',
            field=models.CharField(blank=True, max_length=2055, null=True, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='property',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='property',
            name='perprice',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='phone',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(max_length=10, validators=[developer.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.CharField(max_length=50, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_ft',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='taluk',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='whatsapp',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='categories',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_text_min_3]),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='label',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_text_min_3]),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='locations',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_text_min_3]),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='owner',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_text_min_3]),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='phone',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='pin_code',
            field=models.CharField(max_length=8, validators=[developer.validators.validate_pincode]),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='purposes',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_text_min_3]),
        ),
        migrations.AlterField(
            model_name='propertylist',
            name='whatsapp',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='purpose',
            name='name',
            field=models.CharField(max_length=50, unique=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='reelpackage',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='reelpackage',
            name='duration',
            field=models.CharField(max_length=50, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='reelpackage',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='reelpackage',
            name='reel_format',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='request',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_email]),
        ),
        migrations.AlterField(
            model_name='request',
            name='message',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='request',
            name='name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_agent_name]),
        ),
        migrations.AlterField(
            model_name='request',
            name='phone',
            field=models.CharField(max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='subcategoryfield',
            name='field_name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan_name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='mobile',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='name',
            field=models.CharField(max_length=100, validators=[developer.validators.validate_username]),
        ),
        migrations.AlterField(
            model_name='usercreate',
            name='password',
            field=models.CharField(max_length=128, validators=[developer.validators.validate_password]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='bulk_whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='edit_option',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='lead_followup_support',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='matching_clients',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='meta_ads_promotion',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='offline_agent_share',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='poster_creation',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='social_media_marketing',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='top_priority_search',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='alternate_mobile',
            field=models.CharField(blank=True, max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, validators=[developer.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='userupgrade',
            name='best',
            field=models.CharField(help_text='Best suited for', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userupgrade',
            name='genuine',
            field=models.CharField(help_text='Matching genuine clients', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userupgrade',
            name='lead_follow',
            field=models.CharField(help_text='Lead followup support', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userupgrade',
            name='listing',
            field=models.CharField(help_text='Example: 2 Residential / 1 Commercial', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userupgrade',
            name='name',
            field=models.CharField(max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='userupgrade',
            name='social_media',
            field=models.CharField(help_text='Social media marketing duration', max_length=255, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.DeleteModel(
            name='UserAdd',
        ),
    ]
