# Generated by Django 5.2 on 2026-05-13 11:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0012_property_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyenquiry',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
