# Generated by Django 5.2 on 2026-04-30 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0012_alter_advertisement_feature_alter_advertisement_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyenquiry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
