# Generated by Django 5.2 on 2025-12-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0013_property_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='amenities',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.CharField(max_length=10000),
        ),
    ]
