# Generated by Django 5.2 on 2026-04-30 08:57

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0013_alter_propertyenquiry_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreate',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[developer.validators.validate_password]),
        ),
    ]
