# Generated by Django 5.2 on 2025-12-16 10:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0014_alter_property_amenities_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredproperty',
            name='added_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='amenities',
            field=models.CharField(blank=True, max_length=2255, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='label',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='land_area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='land_mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='owner',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='paid',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='state',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='taluk',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='village',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='whatsapp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='property',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.URLField(max_length=1000),
        ),
    ]
