# Generated by Django 5.2 on 2026-04-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0014_alter_usercreate_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyenquiry',
            name='owner',
        ),
    ]
