# Generated by Django 5.2 on 2026-05-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0015_property_selling_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='key_selling_points',
        ),
    ]
