# Generated by Django 5.2 on 2026-05-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0015_remove_propertyenquiry_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreate',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('owner', 'Owner')], default='user', max_length=10),
        ),
    ]
