# Generated by Django 5.2 on 2025-12-16 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0015_alter_expiredproperty_added_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredproperty',
            name='market_staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='market_staff',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
