# Generated by Django 5.2 on 2026-05-19 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0016_remove_property_key_selling_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='key_selling_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
