# Generated by Django 5.2 on 2025-12-16 12:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0016_expiredproperty_market_staff_property_market_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredpremium',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expiredpremium',
            name='duration_days',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='premium',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='premium',
            name='duration_days',
            field=models.PositiveIntegerField(default=365),
        ),
    ]
