# Generated by Django 5.2 on 2026-05-08 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0016_usercreate_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(default='owner', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='userplan',
            name='plan_type',
            field=models.CharField(default='owner', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='userplan',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
