# Generated by Django 5.2 on 2026-05-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0017_property_key_selling_points_propertyimage_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='key_selling_points',
        ),
    ]
