# Generated by Django 5.2 on 2026-05-08 08:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0017_subscription_plan_type_subscription_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupgrade',
            name='plan_type',
            field=models.CharField(default='owner_upgrade_plan', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='userupgrade',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
