# Generated by Django 5.2 on 2025-12-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0017_alter_expiredpremium_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='duration_days',
            field=models.PositiveIntegerField(db_index=True, default=365),
        ),
        migrations.AlterField(
            model_name='property',
            name='duration_days',
            field=models.PositiveIntegerField(db_index=True, default=30),
        ),
    ]
