# Generated by Django 5.2 on 2026-05-19 11:58

import cloudinary.models
import developer.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0018_remove_property_key_selling_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='features',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='property',
            name='key_selling_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='PropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, validators=[developer.validators.validate_safe_text])),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.subcategoryfield')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_features', to='developer.property')),
            ],
        ),
    ]
