# Generated by Django 5.2 on 2025-12-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0018_alter_premium_duration_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expireagents',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
