# Generated by Django 5.2 on 2026-05-08 08:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0018_userupgrade_plan_type_userupgrade_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumplan',
            name='plan_type',
            field=models.CharField(default='premium', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='premiumplan',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
