# Generated by Django 5.2 on 2025-12-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0019_alter_expireagents_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiredproperty',
            name='property_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
