# Generated by Django 5.2 on 2026-05-08 09:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0019_premiumplan_plan_type_premiumplan_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentplan',
            name='plan_type',
            field=models.CharField(default='basic', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='agentplan',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='plan_type',
            field=models.CharField(default='elite', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='eliteplan',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
