# Generated by Django 5.2 on 2026-05-19 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0020_remove_property_key_selling_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='dynamic_fields',
        ),
    ]
