# Generated by Django 5.2 on 2026-02-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0020_expiredproperty_property_code_property_property_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
