# Generated by Django 5.2 on 2026-05-08 09:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0020_agentplan_plan_type_agentplan_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementpackage',
            name='plan_type',
            field=models.CharField(default='advertisement', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='advertisementpackage',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reelpackage',
            name='plan_type',
            field=models.CharField(default='reel', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='reelpackage',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True),
        ),
    ]
