# Generated by Django 5.2 on 2026-05-19 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0021_remove_property_dynamic_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='features',
        ),
    ]
