# Generated by Django 5.2 on 2026-02-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0021_property_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogadmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='message',
            field=models.CharField(blank=True, max_length=2055, null=True),
        ),
    ]
