# Generated by Django 5.2 on 2026-05-21 07:26

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0023_property_owner_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='owner_name',
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
    ]
