# Generated by Django 5.2 on 2026-05-21 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0024_remove_property_owner_name_alter_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner',
            new_name='owner_name',
        ),
        migrations.AddField(
            model_name='property',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='developer.usercreate'),
        ),
    ]
