# Generated by Django 5.2 on 2026-05-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0025_rename_owner_property_owner_name_property_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='owner_name',
            new_name='owner',
        ),
    ]
