# Generated by Django 5.2 on 2026-05-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0027_budget_created_at_alter_budget_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='commercial_property_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='residential_property_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_property_used',
            field=models.IntegerField(default=0),
        ),
    ]
