# Generated by Django 5.2 on 2026-06-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0029_userplansubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplansubscription',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
