# Generated by Django 5.2 on 2026-06-03 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0030_userplansubscription_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplansubscription',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
