# Generated by Django 5.2 on 2026-06-03 06:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0031_userplansubscription_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userplansubscription',
            name='uuid',
            field=models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
