# Generated by Django 5.2 on 2026-06-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0032_alter_userplansubscription_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplansubscription',
            name='edit_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
