# Generated by Django 5.2 on 2026-06-05 09:13

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0033_userplansubscription_edit_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='eliteplan',
            name='edit',
            field=models.CharField(blank=True, help_text='Edit permission for listings', max_length=100, null=True, validators=[developer.validators.validate_safe_text]),
        ),
    ]
