# Generated by Django 5.2 on 2026-06-06 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_inbox_id'),
        ('developer', '0034_eliteplan_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='pending_registration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='agents.pendingagentregistration'),
        ),
    ]
