# Generated by Django 5.2 on 2026-06-06 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_alter_inbox_id'),
        ('developer', '0036_alter_subscription_agent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='agents.agentuserprofile'),
        ),
    ]
