# Generated by Django 5.2 on 2026-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0037_alter_subscription_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='edit_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
