# Generated by Django 5.2 on 2026-06-08 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0038_subscription_edit_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='edit_limit',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
