# Generated by Django 5.2 on 2026-06-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0039_subscription_edit_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eliteplan',
            old_name='sale_listings_limit',
            new_name='featured_listings_limit',
        ),
    ]
