# Generated by Django 5.2 on 2026-06-08 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0040_remove_eliteplan_sale_listings_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eliteplan',
            name='featured_listings_limit',
            field=models.PositiveIntegerField(default=10, help_text='Number of featured listings allowed'),
        ),
    ]
