# Generated by Django 5.2 on 2026-06-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0041_alter_eliteplan_featured_listings_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='featured_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='featured_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
