# Generated by Django 5.2 on 2026-06-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0042_subscription_featured_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(default='owner', max_length=20),
        ),
    ]
