# Generated by Django 5.2 on 2026-06-11 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0043_alter_subscription_plan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='developer.userplansubscription'),
        ),
    ]
