# Generated by Django 5.2 on 2026-06-11 11:50

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0044_property_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='land_area',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
    ]
