# Generated by Django 5.2 on 2026-06-19 06:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0045_alter_property_district_alter_property_land_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SinglePropertyPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_listing_limit', models.PositiveIntegerField(default=1)),
                ('residential_commercial_listing', models.CharField(default='Any Property', max_length=255)),
                ('enquiry_limit', models.PositiveIntegerField(default=1)),
                ('edit_limit', models.PositiveIntegerField(default=2)),
                ('matching_clients', models.CharField(default='All Verified Users', max_length=255)),
                ('property_visibility', models.CharField(default='Middle Priority + Standard Visibility', max_length=255)),
                ('top_priority_search', models.BooleanField(default=True)),
                ('meta_ads_days', models.PositiveIntegerField(default=7)),
                ('whatsapp_bulk_limit', models.PositiveIntegerField(default=2)),
                ('offline_agent_share_limit', models.PositiveIntegerField(default=5)),
                ('poster_creation_limit', models.PositiveIntegerField(default=1)),
                ('social_media_marketing_weeks', models.PositiveIntegerField(default=1)),
                ('lead_followup_support', models.BooleanField(default=False)),
                ('best_suited_for', models.CharField(default='Single Property Rental Owners', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Single Property Package',
                'verbose_name_plural': 'Single Property Packages',
                'ordering': ['price'],
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='plan_type',
            field=models.CharField(choices=[('user_plan', 'User Plan'), ('premium', 'Premium'), ('elite', 'Elite'), ('agent', 'Agent'), ('single_property', 'Single Property')], max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='single_property_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='developer.singlepropertypackage'),
        ),
    ]
