# Generated by Django 5.2 on 2026-06-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0046_singlepropertypackage_alter_payment_plan_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='singlepropertypackage',
            name='description',
        ),
    ]
