# Generated by Django 5.2 on 2026-06-25 07:03

import developer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0047_remove_singlepropertypackage_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='id',
            field=models.UUIDField(default=developer.models.generate_global_property_uuid, editable=False, primary_key=True, serialize=False),
        ),
    ]
