# Generated by Django 5.2 on 2026-06-25 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0048_alter_property_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='single_property_edit_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='single_property_edit_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='property',
            name='single_property_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.singlepropertypackage'),
        ),
    ]
