# Generated by Django 5.2 on 2026-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0050_payment_reel_package_reelpurchasenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='plan_type',
            field=models.CharField(choices=[('user_plan', 'User Plan'), ('premium', 'Premium'), ('elite', 'Elite'), ('agent', 'Agent'), ('single_property', 'Single Property'), ('short_reel', 'Short Reel'), ('cinematic_reel', 'Cinematic Reel')], max_length=50),
        ),
    ]
