# Generated by Django 5.2 on 2026-06-27 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentproperty_id'),
        ('developer', '0051_alter_payment_plan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementRequestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('advertisement_request', 'Advertisement Request')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advertisement_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.advertisementpackage')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agents.agentuserprofile')),
            ],
        ),
    ]
