# Generated by Django 5.2 on 2026-06-29 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0052_advertisementrequestnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='commercial_property_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='residential_property_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='total_property_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
