# Generated by Django 5.2 on 2026-06-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0053_alter_userprofile_commercial_property_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplansubscription',
            name='commercial_property_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplansubscription',
            name='residential_property_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userplansubscription',
            name='total_property_used',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
