# Generated by Django 5.2 on 2026-07-02 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0054_userplansubscription_commercial_property_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementrequestnotification',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
