# Generated by Django 5.2 on 2026-07-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0055_advertisementrequestnotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelpurchasenotification',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='requested', max_length=20),
        ),
    ]
