# Generated by Django 5.2 on 2026-07-02 09:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0056_reelpurchasenotification_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementrequestnotification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reelpurchasenotification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
