# Generated by Django 5.2 on 2026-07-02 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0057_alter_advertisementrequestnotification_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reelpurchasenotification',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('contacted', 'Contacted'), ('completed', 'Completed')], default='in_progress', max_length=20),
        ),
    ]
