# Generated by Django 5.2 on 2026-07-04 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0058_alter_reelpurchasenotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementrequestnotification',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advertisement_notifications', to='developer.payment'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='developer.payment'),
        ),
    ]
