# Generated by Django 5.2 on 2026-07-04 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0059_advertisementrequestnotification_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisementrequestnotification',
            name='payment',
        ),
    ]
