# Generated by Django 5.2 on 2026-07-30 06:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0010_alter_agentproperty_id'),
        ('developer', '0060_remove_advertisementrequestnotification_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expireagents',
            name='agentscity',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='agentsemail',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='agentsimage',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='agentslocation',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='agentsname',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='agentsphone',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='agentspincode',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='agentsspeacialised',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='agentswhatsapp',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='expireagents',
            name='duration_days',
        ),
        migrations.AddField(
            model_name='expireagents',
            name='agent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expired_record', to='agents.agentuserprofile'),
        ),
        migrations.AddField(
            model_name='expireagents',
            name='expired_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expireagents',
            name='reason',
            field=models.CharField(default='Subscription Expired', max_length=100),
        ),
        migrations.AddField(
            model_name='expireagents',
            name='renewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expireagents',
            name='renewed_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expireagents',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.subscription'),
        ),
    ]
