# Generated by Django 5.2 on 2026-07-30 11:04

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0061_remove_expireagents_agentscity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredproperty',
            name='note',
            field=models.TextField(blank=True, null=True, validators=[developer.validators.validate_safe_message]),
        ),
    ]
