# Generated by Django 5.2 on 2026-08-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0062_alter_expiredproperty_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='reelpackage',
            name='edited_video',
            field=models.BooleanField(default=False),
        ),
    ]
