# Generated by Django 5.2 on 2026-08-04 11:12

import cloudinary.models
import developer.models
import developer.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0062_alter_expiredproperty_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expiredproperty',
            options={'ordering': ['-created_at'], 'verbose_name': 'Expired Property', 'verbose_name_plural': 'Expired Properties'},
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='deposit',
            field=models.CharField(blank=True, default='', max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='message',
            field=models.CharField(blank=True, max_length=2055, null=True, validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expired_properties', to='developer.userplan'),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='selling_points',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='single_property_edit_limit',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='single_property_edit_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='single_property_package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='developer.singlepropertypackage'),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expired_properties', to='developer.userplansubscription'),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='expiredproperty',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expired_properties', to='developer.usercreate'),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='description',
            field=models.TextField(validators=[developer.validators.validate_safe_message]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='duration_days',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='id',
            field=models.UUIDField(default=developer.models.generate_global_property_uuid, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='land_area',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='land_mark',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='location',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='owner',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[developer.validators.validate_safe_text]),
        ),
        migrations.AlterField(
            model_name='expiredproperty',
            name='paid',
            field=models.CharField(default='no', max_length=50),
        ),
        migrations.CreateModel(
            name='ExpiredPropertyFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('icon', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_features', to='developer.expiredproperty')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='developer.subcategoryfield')),
            ],
        ),
    ]
