# Generated by Django 5.2 on 2026-08-27 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0063_alter_expiredproperty_options_and_more'),
        ('developer', '0063_reelpackage_edited_video'),
    ]

    operations = [
    ]
