# Generated by Django 5.2 on 2026-09-10 06:29

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0065_adminnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[developer.validators.validate_pincode]),
        ),
    ]
