# Generated by Django 5.2 on 2026-09-12 04:56

import developer.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developer', '0066_alter_property_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expiredproperty',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[developer.validators.validate_pincode]),
        ),
    ]
